-- Append-only audit trail for administrative configuration changes. The
-- trigger owns writes; authenticated clients receive SELECT access only for
-- their own organization and cannot update or delete audit records.

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_user_id uuid,
  table_name text NOT NULL,
  record_id text,
  action text NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_log_org_created_idx
  ON public.admin_audit_log (org_id, created_at DESC);

ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_audit_log_select_authenticated_org
  ON public.admin_audit_log;
CREATE POLICY admin_audit_log_select_authenticated_org
  ON public.admin_audit_log
  FOR SELECT
  TO authenticated
  USING (org_id = provider_matcher_private.get_user_org_id());

CREATE OR REPLACE FUNCTION provider_matcher_private.write_admin_audit_log()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_old jsonb;
  v_new jsonb;
  v_row jsonb;
  v_org_id uuid;
  v_record_id text;
  v_provider_id uuid;
BEGIN
  v_old := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END;
  v_new := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END;
  v_row := COALESCE(v_new, v_old);
  v_record_id := v_row ->> 'id';

  IF TG_TABLE_NAME = 'organizations' THEN
    v_org_id := (v_row ->> 'id')::uuid;
  ELSIF TG_TABLE_NAME = 'provider_locations' THEN
    v_provider_id := (v_row ->> 'provider_id')::uuid;
    SELECT p.org_id INTO v_org_id
    FROM public.providers AS p
    WHERE p.id = v_provider_id;
  ELSE
    v_org_id := (v_row ->> 'org_id')::uuid;
  END IF;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Cannot determine organization for audit record on %', TG_TABLE_NAME;
  END IF;

  INSERT INTO public.admin_audit_log (
    org_id,
    actor_user_id,
    table_name,
    record_id,
    action,
    old_data,
    new_data
  )
  VALUES (
    v_org_id,
    auth.uid(),
    TG_TABLE_NAME,
    v_record_id,
    TG_OP,
    v_old,
    v_new
  );

  RETURN COALESCE(NEW, OLD);
END;
$$;

REVOKE ALL ON FUNCTION provider_matcher_private.write_admin_audit_log() FROM PUBLIC;
REVOKE ALL ON FUNCTION provider_matcher_private.write_admin_audit_log() FROM anon;
REVOKE ALL ON FUNCTION provider_matcher_private.write_admin_audit_log() FROM authenticated;

DO $create_audit_triggers$
DECLARE
  v_table text;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'locations',
    'case_types',
    'categories',
    'providers',
    'provider_locations',
    'constraints',
    'offerings',
    'questions',
    'widgets',
    'import_history'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', 'audit_' || v_table, v_table);
    EXECUTE format(
      'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I '
      || 'FOR EACH ROW EXECUTE FUNCTION provider_matcher_private.write_admin_audit_log()',
      'audit_' || v_table,
      v_table
    );
  END LOOP;
END;
$create_audit_triggers$;

-- Organization deletion cannot be written to this same table because the
-- referenced organization no longer exists by the time an AFTER DELETE
-- trigger runs. Record organization creates/updates here; organization
-- deletion must be retained in the external platform/database audit log.
DROP TRIGGER IF EXISTS audit_organizations ON public.organizations;
CREATE TRIGGER audit_organizations
AFTER INSERT OR UPDATE ON public.organizations
FOR EACH ROW EXECUTE FUNCTION provider_matcher_private.write_admin_audit_log();

-- ROLLBACK (manual): drop audit_* triggers on the listed tables, then drop
-- provider_matcher_private.write_admin_audit_log() and public.admin_audit_log.
